---

config:
  build_site24x7: False
  build_tbpulumi: True

resources:
  tb:secrets:PulumiSecretsManager:
    secrets:
      secret_names:
        - posthog_api_key

  tb:cloudwatch:LogDestination:
    observability:
      log_group:
        retention_in_days: 7
      log_streams:
        untagged: untagged
      org_name: tb

  tb:network:MultiCidrVpc:
    fluentbit:
      # The observability project has all of 10.202.0.0/16 assigned to it, but let's not soak all
      # those up just serving fluent-bit. This CIDR gets us 10.202.0.0 -> 10.202.3.255.
      cidr_block: 10.202.0.0/22
      subnets:
        eu-central-1a:
          - 10.202.0.0/23  # 10.202.0.0 - 10.202.1.255
        eu-central-1b:
          - 10.202.2.0/23  # 10.202.2.0 - 10.202.3.255
      # Allow traffic out via an IGW so we can talk to Posthog and other services
      enable_internet_gateway: True
      egress_via_internet_gateway: True
      # Required for load balancing Fargate containers
      enable_dns_hostnames: True
      endpoint_interfaces:
        - logs
        - secretsmanager
      additional_routes:
        - destination_cidr_block: 10.2.0.0/16  # mailstrom-dev
          vpc_peering_connection_id: pcx-0d2027442f0e54ca4

  tb:fargate:AutoscalingFargateCluster:
    fluentbit:
      cluster: {}

      container_security_groups:
        fluentbit: # Service
          fluentbit: # Load Balancer
            rules:
              ingress:
                # Maddeningly, apostrophes aren't allowed in descriptions
                - description: Allow traffic from the load balancer to the containers HTTP service
                  # Sources are set in code
                  protocol: tcp
                  from_port: 1337
                  to_port: 1337
                - description: Allow traffic from the load balancer to the containers log forwarding service
                  # Sources are set in code
                  protocol: tcp
                  from_port: 24224
                  to_port: 24224
              egress:
                - description: Allow traffic from the container out to the Internet
                  protocol: tcp
                  from_port: 0
                  to_port: 65535
                  cidr_blocks:
                    - 0.0.0.0/0

      secrets:
        fluentbit:
          - arn:aws:secretsmanager:eu-central-1:768512802988:secret:observability/dev/posthog_api_key*
      
      ssm_params: {}

      task_definitions:
        fluentbit: # Service
          container_definitions:
            - name: fluentbit
              environment:
                - name: ENV
                  value: dev
                - name: FLUENTBIT_LOG_LEVEL
                  value: info
                - name: FLUENTBIT_VERSION
                  value: 4.2.2
                - name: FLUENTBIT_STALWART_DELETE_KEYS
                  value: contents
                - name: FLUENTBIT_STALWART_HASH_KEYS
                  value: from,to
              secrets:
                - name: POSTHOG_API_KEY
                  valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:observability/dev/posthog_api_key-e3UEK4
              image: 768512802988.dkr.ecr.eu-central-1.amazonaws.com/thunderbird/fluent-bit:0bc8e6cdee4226f9c090ca22b08b3f6c61a5456a2090669414a43c52dd2580a8
              logConfiguration:
                logDriver: awslogs
                options:
                  awslogs-group: /tb/dev/observability
                  awslogs-region: eu-central-1
                  awslogs-stream-prefix: 'ecs'
              portMappings:
                - containerPort: 1337
                  protocol: tcp
                - containerPort: 24224
                  protocol: tcp
              restartPolicy:
                enabled: yes
                restartAttemptPeriod: 300
          cpu: 512
          family: fluentbit
          memory: 1024
          network_mode: awsvpc
          requires_compatibilities:
            - FARGATE

      load_balancer_security_groups:
        fluentbit: # Load Balancer
          description: Governs access to the fluentbit-http load balancer in dev
          rules:
            ingress:
              - from_port: 443
                to_port: 443
                protocol: tcp
                cidr_blocks:
                  - 10.2.0.0/16  # stalwart-dev
                description: Allow access to telemetry forwarding service from stalwart-dev
              - from_port: 24224
                to_port: 24224
                protocol: tcp
                cidr_blocks:
                  - 10.2.0.0/16  # stalwart-dev
                description: Allow access to log forwarding service from stalwart-dev
            egress:
              - from_port: 0
                to_port: 65535
                protocol: all
                cidr_blocks:
                  - 0.0.0.0/0

      load_balancers:
        fluentbit:
          enable_cross_zone_load_balancing: yes
          internal: yes
          ip_address_type: ipv4
          load_balancer_type: network
          name: obsv-dev-fluentbit
          preserve_host_header: yes

      targets:
        cwlogs:
          name: obsv-dev-fluent-logs
          health_check:
            port: 24224
            protocol: TCP
          port: 24224
          protocol: TCP
          target_type: ip
          ip_address_type: ipv4
        stalwart-metrics:
          name: obsv-dev-fluent-telemetry
          health_check:
            port: 1337
            protocol: TCP
          port: 1337
          protocol: TCP
          target_type: ip
          ip_address_type: ipv4

      listeners:
        fluentbit: # Load Balancer
          cwlogs: # Target
            port: 24224
            protocol: TCP
          stalwart-metrics: # Target
            port: 443
            protocol: TLS
            # This cert is for fluentbit-dev.tb.pro
            certificate_arn: arn:aws:acm:eu-central-1:768512802988:certificate/04dd0573-a3cc-4c19-b483-a868876c63b0

      services:
        fluentbit: # Service
          assign_public_ip: yes
          container_name: fluentbit  # Name from container definition
          container_port: 1337
          load_balancer: fluentbit
          service:
            desired_count: 2
          targets:
            - container_name: fluentbit
              container_port: 24224
              target_name: cwlogs
            - container_name: fluentbit
              container_port: 1337
              target_name: stalwart-metrics
      
      extra_policies:
        fluentbit:
          - arn:aws:iam::768512802988:policy/mailstrom-dev-stalwart-logs-write-access
          - arn:aws:iam::768512802988:policy/observability-dev-observability-logs-write-access

      autoscalers:
        fluentbit:
          min_capacity: 2
          max_capacity: 4