---

service:
  flush: 1
  grace: 5
  daemon: no
  dns.mode: UDP
  hot_reload: on
  log_level: info
  storage.path: /fluent-bit/buffers
  storage.backlog.flush_on_shutdown: on
  storage.keep.rejected: on
  storage.rejected.path: /fluent-bit/dlq

pipeline:
  inputs:
    - name: http
      tag: untagged
      port: 1337
      threaded: true

  filters:
    # Run a Lua script that breaks all events in a single Stalwart telemetry payload into multiple
    # records. The tag "telemetry_stalwart" here is the result of POSTing to the http input at the
    # path `/telemetry/stalwart`.
    - name: lua
      match: telemetry_stalwart
      script: /etc/fluent-bit/lua/stalwart_telemetry_events.lua
      call: stalwart_telemetry_callback

  outputs:
    # Throw away health checks
    - name: null
      match: health_check

    # Log untagged records so we can respond to them
    - name: file
      match: untagged
      path: /fluent-bit/outputs
      file: untagged.log
      format: out_file

    # Send Stalwart telemetry to Posthog
    - name: http
      match: telemetry_stalwart
      host: us.i.posthog.com
      port: 443
      tls: on
      uri: /batch
      format: json_lines
